import { GraphQLModel } from '../GraphQLParser.js';
import { toCamelCase } from './helpers.js';
import { DelegateHelpers } from './DelegateHelpers.js';
import { DelegateRelations } from './DelegateRelations.js';

export class DelegateGenerator {
  private helpers = new DelegateHelpers();
  private relations = new DelegateRelations();

  generateModelsIndex(models: GraphQLModel[]): string {
    return models.map(model => `export { ${model.name}Delegate } from './${model.name}'`).join('\n');
  }

  generateModelFiles(models: GraphQLModel[]): Record<string, string> {
    const files: Record<string, string> = {};
    for (const model of models) {
      files[`models/${model.name}.ts`] = this.generateModelDelegate(model);
    }
    return files;
  }

  generateModelDelegate(model: GraphQLModel): string {
    const hasCascade = model.relations.some(r => r.onDelete !== 'NoAction');
    const hasCascadeUpdate = model.relations.some(r => r.onUpdate && r.onUpdate !== 'NoAction');
    const hasGenerator = model.fields.some(f => f.defaultGenerator);
    const hasValidation = model.fields.some(f => f.validationRules);
    const validationMethod = hasValidation ? this.helpers.generateValidationMethod(model) : '';
    const validateCall = hasValidation ? `\n      this.validateData(data)` : '';
    const cascadeMethod = this.helpers.generateCascadeMethod(model);
    const cascadeUpdateMethod = hasCascadeUpdate ? this.helpers.generateCascadeUpdateMethod(model) : '';
    const cascadeUpdateCall = hasCascadeUpdate ? `\n      await this.handleCascadeUpdate(formatted, preRelationDoc)` : '';
    const cascadeDeleteCall = hasCascade ? `\n    await this.handleCascadeDelete(doc)` : '';
    const cascadeDeleteManyBody = hasCascade
      ? `    const whereMany = args.where ? await this.processRelationFilters(args.where) : {}
    const query = QueryBuilder.buildWhere(whereMany)
    const dbOptions = args.session ? { session: args.session } : {}
    const docs = await this.collection.find(query, dbOptions).toArray()
    for (const doc of docs) {
      await this.handleCascadeDelete(doc)
    }
    const result = await this.collection.deleteMany(query, dbOptions)
    return { count: result.deletedCount }`
      : `    const whereMany = args.where ? await this.processRelationFilters(args.where) : {}
    const query = QueryBuilder.buildWhere(whereMany)
    const dbOptions = args.session ? { session: args.session } : {}
    const result = await this.collection.deleteMany(query, dbOptions)
    return { count: result.deletedCount }`;

    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

import { Collection, ObjectId, Document } from 'mongodb'
import type {
  ${model.name},
  ${model.name}CreateInput,
  ${model.name}UpdateInput,
  ${model.name}WhereInput,
  ${model.name}WhereUniqueInput,
  ${model.name}QueryOptions,
  ${model.name}CreateArgs,
  ${model.name}UpdateArgs,
  ${model.name}DeleteArgs,
  ${model.name}UpsertArgs,
  ${model.name}FindUniqueArgs,
  ${model.name}FindUniqueOrThrowArgs,
  ${model.name}FindFirstOrThrowArgs,
  ${model.name}AggregateArgs,
  ${model.name}AggregateResult
} from '../types'
import { QueryBuilder } from '../runtime/query'
import { PaginationHelper } from '../runtime/pagination'
import { RelationResolver } from '../runtime/relations'
import { wrapMongoError } from '../runtime/errors'
import { NotFoundError } from '../runtime/errors'
${hasGenerator ? "import crypto from 'crypto'\n" : ''}import type { LenzClient } from '../client'

export class ${model.name}Delegate {
  constructor(private client: LenzClient) {}

  private modelName = '${model.name}';

  private async execute<T>(name: string, fn: () => Promise<T>, context?: any): Promise<T> {
    const queryExt = this.client.getQueryExtension(this.modelName, name)
    if (queryExt) {
      return queryExt({
        args: context || {},
        query: async () => {
          return this.executeRaw(name, fn)
        }
      })
    }
    return this.executeRaw(name, fn)
  }

  private async executeRaw<T>(name: string, fn: () => Promise<T>): Promise<T> {
    const start = Date.now()
    try {
      let result = await fn()
      const duration = Date.now() - start
      this.client.logger.query({ method: name, duration, timestamp: new Date() })

      const resultExts = this.client.getResultExtensions(this.modelName)
      if (resultExts && result) {
        if (Array.isArray(result)) {
          result = result.map(item => this.applyResultExtensions(item, resultExts)) as any
        } else if (typeof result === 'object' && result !== null) {
          result = this.applyResultExtensions(result, resultExts) as any
        }
      }

      return result
    } catch (error) {
      const duration = Date.now() - start
      this.client.logger.query({ method: name, duration, timestamp: new Date() })
      throw wrapMongoError(error, \`\${this.constructor.name}.\${name}\`)
    }
  }

  private applyResultExtensions(item: any, exts: Array<{ name: string; compute: (parent: any) => any }>): any {
    if (!item || typeof item !== 'object') return item
    for (const ext of exts) {
      item[ext.name] = ext.compute(item)
    }
    return item
  }

  private readonly hiddenFields: string[] = ${JSON.stringify(model.fields.filter(f => f.isHidden).map(f => f.name))};

  private readonly fieldMapping: Record<string, string> = ${JSON.stringify(
    Object.fromEntries(
      model.fields.filter(f => f.dbName).map(f => [f.name, f.dbName!])
    )
  )};

  private readonly relationFilters: Array<{ field: string; foreignKey: string; target: string; isArray: boolean }> = ${JSON.stringify(
    model.relations
      .filter(r => r.foreignKey && !r.joinCollection)
      .map(r => ({ field: r.field, foreignKey: r.foreignKey!, target: r.target, isArray: r.isForeignKeyArray }))
  )};

  private async processRelationFilters(where: any): Promise<any> {
    if (!where || this.relationFilters.length === 0) return where;
    let result = { ...where };
    for (const rel of this.relationFilters) {
      const relFilter = result[rel.field];
      if (!relFilter) continue;

      const targetCol = this.client.$db.collection(rel.target.toLowerCase() + 's');

      if (relFilter.is || relFilter.isNot) {
        const subWhere = relFilter.is || relFilter.isNot;
        const useIn = !!relFilter.is;
        const matchingDocs = await targetCol.find(QueryBuilder.buildWhere(subWhere), { projection: { _id: 1 } }).toArray();
        const matchingIds = matchingDocs.map((d: any) => d._id.toString());
        if (matchingIds.length > 0 || !useIn) {
          if (rel.isArray) {
            result[rel.foreignKey] = useIn ? { $in: matchingIds } : { $nin: matchingIds };
          } else {
            result[rel.foreignKey] = useIn && matchingIds.length === 1
              ? matchingIds[0]
              : useIn ? { $in: matchingIds } : { $nin: matchingIds };
          }
        }
        delete result[rel.field];
      }

      if (relFilter.some || relFilter.every || relFilter.none) {
        if (relFilter.some) {
          const matchingDocs = await targetCol.find(QueryBuilder.buildWhere(relFilter.some), { projection: { _id: 1 } }).toArray();
          const matchingIds = matchingDocs.map((d: any) => d._id.toString());
          if (matchingIds.length > 0) {
            if (rel.isArray) {
              result[rel.foreignKey] = { $in: matchingIds };
            } else {
              result[rel.foreignKey] = matchingIds.length === 1 ? matchingIds[0] : { $in: matchingIds };
            }
          } else {
            result._id = { $in: [] };
          }
        }
        if (relFilter.every) {
          const nonMatchingDocs = await targetCol.find(
            { $nor: [QueryBuilder.buildWhere(relFilter.every)] },
            { projection: { _id: 1 } }
          ).toArray();
          const nonMatchingIds = nonMatchingDocs.map((d: any) => d._id.toString());
          if (nonMatchingIds.length > 0) {
            if (rel.isArray) {
              result[rel.foreignKey] = { $nin: nonMatchingIds };
            } else {
              result[rel.foreignKey] = { $nin: nonMatchingIds };
            }
          }
        }
        if (relFilter.none) {
          const matchingDocs = await targetCol.find(QueryBuilder.buildWhere(relFilter.none), { projection: { _id: 1 } }).toArray();
          const matchingIds = matchingDocs.map((d: any) => d._id.toString());
          if (matchingIds.length > 0) {
            if (rel.isArray) {
              result[rel.foreignKey] = { $nin: matchingIds };
            } else {
              result[rel.foreignKey] = { $nin: matchingIds };
            }
          }
        }
        delete result[rel.field];
      }
    }
    return result;
  }

  private readonly defaultValues = {
    ${model.fields.filter(f => f.defaultValue !== undefined || f.defaultGenerator !== undefined || (f.isRequired && f.isArray && !f.isId)).map(f => {
      if (f.defaultGenerator === 'now') return `${f.name}: new Date()`;
      if (f.defaultGenerator === 'uuid') return `${f.name}: crypto.randomUUID()`;
      if (f.defaultGenerator === 'cuid') return `${f.name}: 'cuid_' + crypto.randomUUID().slice(0, 8)`;
      if (f.defaultValue !== undefined) return `${f.name}: ${JSON.stringify(f.defaultValue)}`;
      if (f.isRequired && f.isArray && !f.isId) return `${f.name}: []`;
      return '';
    }).filter(Boolean).join(',\n    ')}
  };


  private get collection(): Collection<Document> {
    return this.client.$db.collection('${model.collectionName}')
  }

  async findUnique(args: ${model.name}FindUniqueArgs): Promise<${model.name} | null> {
    return this.execute('findUnique', async () => {
      const processedWhere = await this.processRelationFilters(args.where)
      const query = QueryBuilder.buildWhere(processedWhere)
      const options = QueryBuilder.buildOptions(args, this.hiddenFields, this.fieldMapping)

      const doc = await this.collection.findOne(query, options)
      if (!doc) return null

      const formatted = RelationResolver.formatDocument(doc)

      if (args.include) {
        return await this.includeRelations(formatted, args.include)
      }

      return formatted
    })
  }

  async findUniqueOrThrow(args: ${model.name}FindUniqueOrThrowArgs): Promise<${model.name}> {
    return this.execute('findUniqueOrThrow', async () => {
      const result = await this.findUnique(args)
      if (!result) throw new NotFoundError('${model.name}', { where: args.where })
      return result
    })
  }

  async findMany(args?: ${model.name}QueryOptions): Promise<${model.name}[]> {
    return this.execute('findMany', async () => {
      const { cursor, ...otherArgs } = args || {}
      let where = await this.processRelationFilters(args?.where || {})

      if (cursor) {
        const cursorCondition = QueryBuilder.buildCursorCondition(cursor, args?.orderBy)
        where = {
          ...where,
          ...cursorCondition
        }
      }

      const query = QueryBuilder.buildWhere(where)
      const options = QueryBuilder.buildOptions(otherArgs || {}, this.hiddenFields, this.fieldMapping)

      let docs: any[];

      if (args?.distinct) {
        const distinctFields = Array.isArray(args.distinct) ? args.distinct : [args.distinct]
        const pipeline: any[] = [{ $match: query }]

        const groupId: any = {}
        for (const field of distinctFields) {
          groupId[field] = \`$\${field}\`
        }
        pipeline.push({ $group: { _id: groupId, doc: { $first: '$$ROOT' } } })
        pipeline.push({ $replaceRoot: { newRoot: '$doc' } })

        if (options.sort) { pipeline.push({ $sort: options.sort }) }
        if (options.skip !== undefined) { pipeline.push({ $skip: options.skip }) }
        if (options.limit !== undefined) { pipeline.push({ $limit: options.limit }) }

        const aggCursor = this.collection.aggregate(pipeline, options.session ? { session: options.session } : {})
        docs = await aggCursor.toArray()
      } else {
        const mongoCursor = this.collection.find(query, options)
        docs = await mongoCursor.toArray()
      }

      const formatted = docs.map(RelationResolver.formatDocument)

      if (args?.include) {
        return await Promise.all(
          formatted.map(doc => this.includeRelations(doc, args.include!))
        )
      }

      return formatted
    })
  }

  async findFirst(args?: ${model.name}QueryOptions): Promise<${model.name} | null> {
    return this.execute('findFirst', async () => {
      const results = await this.findMany({ ...args, take: 1 })
      return results[0] || null
    })
  }

  async findFirstOrThrow(args: ${model.name}FindFirstOrThrowArgs): Promise<${model.name}> {
    return this.execute('findFirstOrThrow', async () => {
      const result = await this.findFirst(args)
      if (!result) throw new NotFoundError('${model.name}', { where: args?.where })
      return result
    })
  }

  async create(args: ${model.name}CreateArgs): Promise<${model.name}> {
    return this.execute('create', async () => {
      const now = new Date()
      const parentId = new ObjectId()

      const relationFields = ['${model.relations.filter(r => !r.joinCollection).map(r => r.field).join("', '")}'] as const;
      const nestedData: Record<string, any> = {};
      const scalarData: Record<string, any> = {};
      for (const [key, value] of Object.entries(args.data)) {
        if (relationFields.includes(key as any) && typeof value === 'object' && value !== null && !Array.isArray(value) && !(value as any).equals) {
          nestedData[key] = value;
        } else if (relationFields.includes(key as any) && Array.isArray(value) && value.length > 0 && typeof value[0] === 'object' && !(value[0] as any)?.equals) {
          nestedData[key] = value;
        } else {
          scalarData[key] = value;
        }
      }

      ${validateCall}
      const document = {
        ...this.defaultValues,
        ...scalarData,
        _id: parentId,
        createdAt: now,
        updatedAt: now
      }

      const result = await this.collection.insertOne(document, args.session ? { session: args.session } : {})
      const parentDocId = result.insertedId.toString()

      const postCreateSets: Record<string, any> = {};
      const postCreatePushes: Record<string, any> = {};
      ${model.relations.filter(r => !r.joinCollection).map(rel => {
        const delegate = `this.client.${toCamelCase(rel.target)}`;
        const fkInSource = rel.foreignKeyLocation === 'source' || !rel.foreignKeyLocation;
        const isArray = rel.isForeignKeyArray;
        const childFkArg = (!fkInSource && rel.foreignKey) ? `, ${rel.foreignKey}: parentDocId` : '';
        if (rel.type === 'oneToMany' || rel.type === 'manyToMany') {
          return `
      if (nestedData.${rel.field}) {
        const ${rel.field}Data = nestedData.${rel.field};
        if (${rel.field}Data.create) {
          const created = await Promise.all(
            (Array.isArray(${rel.field}Data.create) ? ${rel.field}Data.create : [${rel.field}Data.create]).map(data =>
              ${delegate}.create({ data: { ...data${childFkArg} } })
            )
          );
          const ids = created.map(c => c.id);
          ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(...ids);` : `postCreateSets.${rel.foreignKey} = ids.length === 1 ? ids[0] : ids;`) : ''}
        }
        if (${rel.field}Data.connect) {
          const connectIds = (Array.isArray(${rel.field}Data.connect) ? ${rel.field}Data.connect : [${rel.field}Data.connect]).map(c => c.id);
          ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(...connectIds);` : `postCreateSets.${rel.foreignKey} = connectIds.length === 1 ? connectIds[0] : connectIds;`) : ''}
        }
        if (${rel.field}Data.connectOrCreate) {
          const items = Array.isArray(${rel.field}Data.connectOrCreate) ? ${rel.field}Data.connectOrCreate : [${rel.field}Data.connectOrCreate];
          for (const item of items) {
            const existing = await ${delegate}.findUnique({ where: item.where });
            if (existing) {
              ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(existing.id);` : `postCreateSets.${rel.foreignKey} = existing.id;`) : ''}
            } else {
              const created = await ${delegate}.create({ data: { ...item.create${childFkArg} } });
              ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(created.id);` : `postCreateSets.${rel.foreignKey} = created.id;`) : ''}
            }
          }
        }
      }`;
        } else {
          return `
      if (nestedData.${rel.field}) {
        const ${rel.field}Data = nestedData.${rel.field};
        if (${rel.field}Data.create) {
          const created = await ${delegate}.create({ data: { ...${rel.field}Data.create${childFkArg} } });
          ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(created.id);` : `postCreateSets.${rel.foreignKey} = created.id;`) : ''}
        }
        if (${rel.field}Data.connect) {
          ${fkInSource ? `postCreateSets.${rel.foreignKey} = ${rel.field}Data.connect.id;` : ''}
        }
        if (${rel.field}Data.connectOrCreate) {
          const existing = await ${delegate}.findUnique({ where: ${rel.field}Data.connectOrCreate.where });
          if (existing) {
            ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(existing.id);` : `postCreateSets.${rel.foreignKey} = existing.id;`) : ''}
          } else {
            const created = await ${delegate}.create({ data: { ...${rel.field}Data.connectOrCreate.create${childFkArg} } });
            ${fkInSource ? (isArray ? `(postCreatePushes.${rel.foreignKey} || (postCreatePushes.${rel.foreignKey} = [])).push(created.id);` : `postCreateSets.${rel.foreignKey} = created.id;`) : ''}
          }
        }
      }`;
        }
      }).join('\n')}

      if (Object.keys(postCreateSets).length > 0 || Object.keys(postCreatePushes).length > 0) {
        const postUpdate: Record<string, any> = {};
        if (Object.keys(postCreateSets).length > 0) postUpdate.$set = postCreateSets;
        if (Object.keys(postCreatePushes).length > 0) postUpdate.$push = postCreatePushes;
        await this.collection.updateOne(
          { _id: parentId },
          postUpdate,
          args.session ? { session: args.session } : {}
        );
      }

      const createdDoc = await this.collection.findOne(
        { _id: parentId },
        args.session ? { session: args.session } : {}
      )

      if (!createdDoc) {
        throw new Error('Failed to create document')
      }

      const formatted = RelationResolver.formatDocument(createdDoc)

      if (args.include) {
        return await this.includeRelations(formatted, args.include)
      }

      return formatted
    })
  }

  async createMany(args: { data: ${model.name}CreateInput[]; session?: any; skipDuplicates?: boolean }): Promise<{ count: number }> {
    return this.execute('createMany', async () => {
      const now = new Date()
      const documents = args.data.map(data => ({
        ...this.defaultValues,
        ...data,
        _id: new ObjectId(),
        createdAt: now,
        updatedAt: now
      }))

      const insertOptions: any = {}
      if (args.session) insertOptions.session = args.session
      if (args.skipDuplicates) {
        insertOptions.ordered = false
      }

      try {
        const result = await this.collection.insertMany(documents, insertOptions)
        return { count: result.insertedCount }
      } catch (error: any) {
        if (args.skipDuplicates && error?.code === 11000) {
          return { count: error?.result?.nInserted || 0 }
        }
        throw error
      }
    })
  }

  async update(args: ${model.name}UpdateArgs): Promise<${model.name}> {
    return this.execute('update', async () => {
      const whereForUpdate = await this.processRelationFilters(args.where)
      const query = QueryBuilder.buildWhere(whereForUpdate)

      const relationFields = ['${model.relations.filter(r => !r.joinCollection).map(r => r.field).join("', '")}'] as const;
      const nestedUpdateData: Record<string, any> = {};
      const scalarUpdateData: Record<string, any> = {};
      for (const [key, value] of Object.entries(args.data)) {
        if (relationFields.includes(key as any) && typeof value === 'object' && value !== null) {
          nestedUpdateData[key] = value;
        } else {
          scalarUpdateData[key] = value;
        }
      }

      const updateData = {
        ...scalarUpdateData,
        updatedAt: new Date()
      }

      const update = QueryBuilder.buildUpdate(updateData)
      const result = await this.collection.findOneAndUpdate(
        query,
        update,
        { returnDocument: 'after', ...(args.session ? { session: args.session } : {}) }
      )

      const updatedDoc = 'value' in result ? result.value : result
      if (!updatedDoc) {
        throw new Error('Document not found')
      }

      const updatedDocId = RelationResolver.formatDocument(updatedDoc).id;
      const preRelationDoc = RelationResolver.formatDocument(updatedDoc);

      const postUpdateSets: Record<string, any> = {};
      const postUpdatePushes: Record<string, any> = {};
      const postUpdatePulls: Record<string, any> = {};
      ${model.relations.filter(r => !r.joinCollection).map(rel => {
        const delegate = `this.client.${toCamelCase(rel.target)}`;
        const fkInSource = rel.foreignKeyLocation === 'source' || !rel.foreignKeyLocation;
        const isArray = rel.isForeignKeyArray;
        const childFkArg = (!fkInSource && rel.foreignKey) ? `, ${rel.foreignKey}: updatedDocId` : '';
        if (rel.type === 'oneToMany' || rel.type === 'manyToMany') {
          return `
      if (nestedUpdateData.${rel.field}) {
        const ${rel.field}Data = nestedUpdateData.${rel.field};
        if (${rel.field}Data.create) {
          const created = await Promise.all(
            (Array.isArray(${rel.field}Data.create) ? ${rel.field}Data.create : [${rel.field}Data.create]).map(data =>
              ${delegate}.create({ data: { ...data${childFkArg} } })
            )
          );
          const ids = created.map(c => c.id);
          ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(...ids);` : `postUpdateSets.${rel.foreignKey} = ids.length === 1 ? ids[0] : ids;`) : ''}
        }
        if (${rel.field}Data.connect) {
          const connectIds = (Array.isArray(${rel.field}Data.connect) ? ${rel.field}Data.connect : [${rel.field}Data.connect]).map(c => c.id);
          ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(...connectIds);` : `postUpdateSets.${rel.foreignKey} = connectIds.length === 1 ? connectIds[0] : connectIds;`) : ''}
        }
        if (${rel.field}Data.connectOrCreate) {
          const items = Array.isArray(${rel.field}Data.connectOrCreate) ? ${rel.field}Data.connectOrCreate : [${rel.field}Data.connectOrCreate];
          for (const item of items) {
            const existing = await ${delegate}.findUnique({ where: item.where });
            if (existing) {
              ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(existing.id);` : `postUpdateSets.${rel.foreignKey} = existing.id;`) : ''}
            } else {
              const created = await ${delegate}.create({ data: { ...item.create${childFkArg} } });
              ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(created.id);` : `postUpdateSets.${rel.foreignKey} = created.id;`) : ''}
            }
          }
        }
        if (${rel.field}Data.disconnect) {
          const disconnectIds = (Array.isArray(${rel.field}Data.disconnect) ? ${rel.field}Data.disconnect : [${rel.field}Data.disconnect]).map(c => c.id);
          ${fkInSource && isArray ? `(postUpdatePulls.${rel.foreignKey} || (postUpdatePulls.${rel.foreignKey} = [])).push(...disconnectIds);` : fkInSource ? `postUpdateSets.${rel.foreignKey} = null;` : ''}
        }
        if (${rel.field}Data.set) {
          const setIds = (Array.isArray(${rel.field}Data.set) ? ${rel.field}Data.set : [${rel.field}Data.set]).map(c => c.id);
          ${fkInSource ? (isArray ? `postUpdateSets.${rel.foreignKey} = setIds;` : `postUpdateSets.${rel.foreignKey} = setIds.length === 1 ? setIds[0] : setIds;`) : ''}
        }
        if (${rel.field}Data.update) {
          const updateItems = Array.isArray(${rel.field}Data.update) ? ${rel.field}Data.update : [${rel.field}Data.update];
          for (const item of updateItems) {
            await ${delegate}.update({ where: item.where, data: item.data });
          }
        }
        if (${rel.field}Data.delete) {
          const deleteItems = Array.isArray(${rel.field}Data.delete) ? ${rel.field}Data.delete : [${rel.field}Data.delete];
          for (const item of deleteItems) {
            await ${delegate}.delete({ where: item });
          }
        }
        if (${rel.field}Data.upsert) {
          const upsertItems = Array.isArray(${rel.field}Data.upsert) ? ${rel.field}Data.upsert : [${rel.field}Data.upsert];
          for (const item of upsertItems) {
            await ${delegate}.upsert({ where: item.where, create: item.create, update: item.update });
          }
        }
        if (${rel.field}Data.updateMany) {
          await ${delegate}.updateMany({ where: ${rel.field}Data.updateMany.where, data: ${rel.field}Data.updateMany.data });
        }
        if (${rel.field}Data.deleteMany) {
          await ${delegate}.deleteMany({ where: ${rel.field}Data.deleteMany });
        }
      }`;
        } else {
          return `
      if (nestedUpdateData.${rel.field}) {
        const ${rel.field}Data = nestedUpdateData.${rel.field};
        if (${rel.field}Data.create) {
          const created = await ${delegate}.create({ data: { ...${rel.field}Data.create${childFkArg} } });
          ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(created.id);` : `postUpdateSets.${rel.foreignKey} = created.id;`) : ''}
        }
        if (${rel.field}Data.connect) {
          ${fkInSource ? `postUpdateSets.${rel.foreignKey} = ${rel.field}Data.connect.id;` : ''}
        }
        if (${rel.field}Data.connectOrCreate) {
          const existing = await ${delegate}.findUnique({ where: ${rel.field}Data.connectOrCreate.where });
          if (existing) {
            ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(existing.id);` : `postUpdateSets.${rel.foreignKey} = existing.id;`) : ''}
          } else {
            const created = await ${delegate}.create({ data: { ...${rel.field}Data.connectOrCreate.create${childFkArg} } });
            ${fkInSource ? (isArray ? `(postUpdatePushes.${rel.foreignKey} || (postUpdatePushes.${rel.foreignKey} = [])).push(created.id);` : `postUpdateSets.${rel.foreignKey} = created.id;`) : ''}
          }
        }
        if (${rel.field}Data.disconnect) {
          ${fkInSource && !isArray ? `postUpdateSets.${rel.foreignKey} = null;` : ''}
        }
        if (${rel.field}Data.update && updatedDoc.${rel.foreignKey}) {
          await ${delegate}.update({ where: { id: String(updatedDoc.${rel.foreignKey}) }, data: ${rel.field}Data.update });
        }
        if (${rel.field}Data.delete && updatedDoc.${rel.foreignKey}) {
          await ${delegate}.delete({ where: { id: String(updatedDoc.${rel.foreignKey}) } });
        }
        if (${rel.field}Data.upsert) {
          await ${delegate}.upsert({ where: ${rel.field}Data.upsert.where, create: ${rel.field}Data.upsert.create, update: ${rel.field}Data.upsert.update });
        }
      }`;
        }
      }).join('\n')}

      if (Object.keys(postUpdateSets).length > 0 || Object.keys(postUpdatePushes).length > 0 || Object.keys(postUpdatePulls).length > 0) {
        const postUpdateCmd: Record<string, any> = {};
        if (Object.keys(postUpdateSets).length > 0) postUpdateCmd.$set = postUpdateSets;
        if (Object.keys(postUpdatePushes).length > 0) postUpdateCmd.$push = { $each: postUpdatePushes };
        if (Object.keys(postUpdatePulls).length > 0) {
          const pullCmd: Record<string, any> = {};
          for (const [field, ids] of Object.entries(postUpdatePulls)) {
            pullCmd[field] = { $in: ids as string[] };
          }
          postUpdateCmd.$pull = pullCmd;
        }
        await this.collection.updateOne(
          { _id: new ObjectId(updatedDocId) },
          postUpdateCmd,
          args.session ? { session: args.session } : {}
        );
      }

      const finalDoc = await this.collection.findOne(
        { _id: new ObjectId(updatedDocId) },
        args.session ? { session: args.session } : {}
      )

      const formatted = RelationResolver.formatDocument(finalDoc || updatedDoc)
${cascadeUpdateCall}
      if (args.include) {
        return await this.includeRelations(formatted, args.include)
      }

      return formatted
    })
  }

  async updateMany(args: { where?: ${model.name}WhereInput; data: ${model.name}UpdateInput; session?: any }): Promise<{ count: number }> {
    return this.execute('updateMany', async () => {
      const whereMany = args.where ? await this.processRelationFilters(args.where) : {}
      const query = QueryBuilder.buildWhere(whereMany)
      const updateData = {
        ...args.data,
        updatedAt: new Date()
      }

      const update = QueryBuilder.buildUpdate(updateData)
      const result = await this.collection.updateMany(query, update, args.session ? { session: args.session } : {})
      return { count: result.modifiedCount }
    })
  }

  async upsert(args: ${model.name}UpsertArgs): Promise<${model.name}> {
    return this.execute('upsert', async () => {
      const whereForUpsert = await this.processRelationFilters(args.where)
      const query = QueryBuilder.buildWhere(whereForUpsert)
      const now = new Date()

      const result = await this.collection.findOneAndUpdate(
        query,
        {
          $set: { ...args.update, updatedAt: now },
          $setOnInsert: { ...args.create, _id: new ObjectId(), createdAt: now, updatedAt: now }
        },
        { returnDocument: 'after', upsert: true, ...(args.session ? { session: args.session } : {}) }
      )

      const doc = 'value' in result ? result.value : result
      if (!doc) {
        throw new Error('Upsert failed')
      }

      const formatted = RelationResolver.formatDocument(doc)

      if (args.include) {
        return await this.includeRelations(formatted, args.include)
      }

      return formatted
    })
  }

  async delete(args: ${model.name}DeleteArgs): Promise<${model.name} | null> {
    return this.execute('delete', async () => {
      const whereForDelete = await this.processRelationFilters(args.where)
      const query = QueryBuilder.buildWhere(whereForDelete)
      const doc = await this.collection.findOne(query, args.session ? { session: args.session } : {})

      if (!doc) return null
${cascadeDeleteCall}
      await this.collection.deleteOne(query, args.session ? { session: args.session } : {})
      const formatted = RelationResolver.formatDocument(doc)

      if (args.include) {
        return await this.includeRelations(formatted, args.include)
      }

      return formatted
    })
  }

  async deleteMany(args: { where?: ${model.name}WhereInput; session?: any }): Promise<{ count: number }> {
    return this.execute('deleteMany', async () => {
${cascadeDeleteManyBody}
    })
  }

  async count(args?: { where?: ${model.name}WhereInput; session?: any }): Promise<number> {
    return this.execute('count', async () => {
      const whereCount = args?.where ? await this.processRelationFilters(args.where) : {}
      const query = QueryBuilder.buildWhere(whereCount)
      return await this.collection.countDocuments(query, args?.session ? { session: args.session } : {})
    })
  }

  async findRaw(filter: any, options?: { session?: any }): Promise<any[]> {
    return this.execute('findRaw', async () => {
      return await this.collection.find(filter, options?.session ? { session: options.session } : {}).toArray()
    })
  }

  async aggregateRaw(pipeline: any[], options?: { session?: any }): Promise<any[]> {
    return this.execute('aggregateRaw', async () => {
      return await this.collection.aggregate(pipeline, options?.session ? { session: options.session } : {}).toArray()
    })
  }

  async aggregate(args: ${model.name}AggregateArgs): Promise<${model.name}AggregateResult> {
    return this.execute('aggregate', async () => {
      const pipeline: any[] = [];

      if (args.where && Object.keys(args.where).length > 0) {
        pipeline.push({ $match: QueryBuilder.buildWhere(args.where) })
      }

      const groupStage: any = { _id: null };

      if (args._count) {
        if (args._count === true) {
          groupStage._count_all = { $sum: 1 }
        } else if (Array.isArray(args._count)) {
          for (const field of args._count) {
            groupStage[\`_count_\${field}\`] = { $sum: 1 }
          }
        }
      }

      for (const op of ['_sum', '_avg', '_min', '_max'] as const) {
        const fields = (args as any)[op];
        if (fields && Array.isArray(fields)) {
          const mongoOp = op === '_sum' ? '$sum' : op === '_avg' ? '$avg' : op === '_min' ? '$min' : '$max';
          for (const field of fields) {
            groupStage[\`\${op}_\${field}\`] = { [mongoOp]: \`$\${field}\` }
          }
        }
      }

      pipeline.push({ $group: groupStage });

      const result = await this.collection.aggregate(pipeline, args.session ? { session: args.session } : {}).toArray()

      if (result.length === 0) return {} as ${model.name}AggregateResult

      const data = result[0];
      const output: any = {};

      if (args._count === true) {
        output._count = data._count_all || 0
      } else if (Array.isArray(args._count)) {
        const countResult: any = {};
        for (const field of args._count) {
          countResult[field] = data[\`_count_\${field}\`] || 0
        }
        output._count = countResult
      }

      for (const op of ['_sum', '_avg', '_min', '_max'] as const) {
        const fields = (args as any)[op];
        if (fields && Array.isArray(fields)) {
          const opResult: any = {};
          for (const field of fields) {
            opResult[field] = data[\`\${op}_\${field}\`] ?? null
          }
          output[op] = opResult
        }
      }

      return output as ${model.name}AggregateResult
    })
  }

  async groupBy(args: ${model.name}GroupByArgs): Promise<${model.name}GroupByResult[]> {
    return this.execute('groupBy', async () => {
      const pipeline: any[] = [];

      if (args.where && Object.keys(args.where).length > 0) {
        pipeline.push({ $match: QueryBuilder.buildWhere(args.where) })
      }

      const groupId: any = {};
      for (const field of args.by) {
        groupId[field] = \`$\${field}\`;
      }

      const groupStage: any = { _id: groupId };

      const addAccumulator = (field: string, op: string, target: string) => {
        if (!groupStage[target]) groupStage[target] = {};
        groupStage[target][field] = { [\`$\${op}\`]: \`$\${field}\` };
      };

      if (args._count) {
        if (args._count === true) {
          groupStage._count = { _all: { $sum: 1 } };
        } else if (Array.isArray(args._count)) {
          groupStage._count = { _all: { $sum: 1 } };
          for (const field of args._count) {
            addAccumulator(field, 'sum', '_count');
          }
        }
      }

      if (args._sum && Array.isArray(args._sum)) {
        for (const field of args._sum) {
          addAccumulator(field, 'sum', '_sum');
        }
      }

      if (args._avg && Array.isArray(args._avg)) {
        for (const field of args._avg) {
          addAccumulator(field, 'avg', '_avg');
        }
      }

      if (args._min && Array.isArray(args._min)) {
        for (const field of args._min) {
          addAccumulator(field, 'min', '_min');
        }
      }

      if (args._max && Array.isArray(args._max)) {
        for (const field of args._max) {
          addAccumulator(field, 'max', '_max');
        }
      }

      pipeline.push({ $group: groupStage });

      const projectStage: any = { _id: 0 };
      for (const field of args.by) {
        projectStage[field] = \`$\${'_id.' + field}\`;
      }

      const aggTargets = ['_count', '_sum', '_avg', '_min', '_max'];
      for (const target of aggTargets) {
        if (groupStage[target]) {
          projectStage[target] = 1;
        }
      }

      if (Object.keys(projectStage).length > 1) {
        pipeline.push({ $project: projectStage });
      }

      if (args.having && Object.keys(args.having).length > 0) {
        pipeline.push({ $match: QueryBuilder.buildWhere(args.having) })
      }

      if (args.orderBy) {
        pipeline.push({ $sort: QueryBuilder.buildSort(args.orderBy) })
      }

      if (args.skip) {
        pipeline.push({ $skip: args.skip })
      }
      if (args.take) {
        pipeline.push({ $limit: args.take })
      }

      const result = await this.collection.aggregate(pipeline, args.session ? { session: args.session } : {}).toArray()
      return result as ${model.name}GroupByResult[]
    })
  }

  private applySelect(document: any, select: any): any {
    if (!select) {
      if (this.hiddenFields.length === 0) return document;
      const result = { ...document };
      this.hiddenFields.forEach(field => {
        delete result[field];
      });
      return result;
    }

    const projection = QueryBuilder.buildProjection(select, this.hiddenFields);
    if (!projection) return document;

    const result = { ...document };
    for (const [field, value] of Object.entries(projection)) {
      if (value === 0 && field in result) {
        delete result[field];
      }
    }
    return result;
  }

  public async includeRelations(document: any, include: any): Promise<any> {
    const result = { ...document }
    if (!include || typeof include !== 'object') {
      return result
    }

    if (include._count && include._count.select) {
      const counts: Record<string, number> = {}
      for (const [relField, shouldCount] of Object.entries(include._count.select)) {
        if (shouldCount) {
${this.relations.generateCountInIncludeCode(model)}
        }
      }
      result._count = counts
    }

${this.relations.generateRelationInclusionCode(model)}

    return result
  }

  get $raw() {
    return {
      collection: this.collection,
      find: async (filter: any) => await this.collection.find(filter).toArray(),
      findOne: async (filter: any) => await this.collection.findOne(filter),
      insertOne: async (doc: any) => await this.collection.insertOne(doc),
      updateOne: async (filter: any, update: any) => await this.collection.updateOne(filter, update),
      deleteOne: async (filter: any) => await this.collection.deleteOne(filter),
      aggregate: async (pipeline: any[]) => await this.collection.aggregate(pipeline).toArray()
    }
  }
}
${cascadeMethod}
${cascadeUpdateMethod}
${validationMethod}
`;
  }
}
