export class RuntimeGenerator {
  generateRuntimePagination(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

import { ObjectId } from 'mongodb'

/**
 * Pagination helper for Lenz ORM
 * Implements both offset-based and cursor-based pagination
 * Similar to Prisma's pagination patterns
 */
export class PaginationHelper {
  static createCursor(doc: any): string {
    if (!doc) throw new Error('Cannot create cursor from null document')
    const id = doc._id || doc.id
    if (!id) throw new Error('Document must have an id to create cursor')
    return Buffer.from(id.toString()).toString('base64')
  }

  static parseCursor(cursor: string): string {
    try {
      return Buffer.from(cursor, 'base64').toString('utf8')
    } catch (error) {
      throw new Error('Invalid cursor format')
    }
  }

  static buildCursorFilter(
    cursor: string,
    orderBy: any = { _id: 'asc' },
    direction: 'forward' | 'backward' = 'forward'
  ): any {
    const cursorId = this.parseCursor(cursor)
    const orderField = Object.keys(orderBy)[0] || '_id'
    const orderDirection = orderBy[orderField] || 'asc'

    const isAscending = orderDirection === 'asc' || orderDirection === 1
    const isForward = direction === 'forward'

    let operator: string
    if (isForward) {
      operator = isAscending ? '$gt' : '$lt'
    } else {
      operator = isAscending ? '$lt' : '$gt'
    }

    return {
      [orderField]: { [operator]: new ObjectId(cursorId) }
    }
  }

  static calculateSkip(page: number, perPage: number): number {
    if (page < 1) throw new Error('Page must be greater than 0')
    return (page - 1) * perPage
  }

  static calculateTotalPages(total: number, perPage: number): number {
    return Math.ceil(total / perPage)
  }

  static getPaginationMeta(
    total: number,
    page: number,
    perPage: number,
    dataLength: number
  ): {
    total: number
    page: number
    perPage: number
    totalPages: number
    hasNextPage: boolean
    hasPreviousPage: boolean
  } {
    const totalPages = this.calculateTotalPages(total, perPage)

    return {
      total,
      page,
      perPage,
      totalPages,
      hasNextPage: page < totalPages,
      hasPreviousPage: page > 1
    }
  }

  static toConnection<T>(
    data: T[],
    totalCount: number,
    hasNextPage: boolean,
    hasPreviousPage: boolean,
    createCursor: (item: T) => string = (item: any) => this.createCursor(item)
  ): {
    edges: Array<{ node: T; cursor: string }>
    pageInfo: {
      hasNextPage: boolean
      hasPreviousPage: boolean
      startCursor?: string
      endCursor?: string
    }
    totalCount: number
  } {
    const edges = data.map(item => ({
      node: item,
      cursor: createCursor(item)
    }))

    return {
      edges,
      pageInfo: {
        hasNextPage,
        hasPreviousPage,
        startCursor: edges[0]?.cursor,
        endCursor: edges[edges.length - 1]?.cursor
      },
      totalCount
    }
  }

  static paginate<T>(
    data: T[],
    page: number = 1,
    perPage: number = 10
  ): {
    data: T[]
    meta: {
      page: number
      perPage: number
      total: number
      totalPages: number
      hasNextPage: boolean
      hasPreviousPage: boolean
    }
  } {
    const startIndex = (page - 1) * perPage
    const endIndex = startIndex + perPage
    const paginatedData = data.slice(startIndex, endIndex)
    const total = data.length
    const totalPages = Math.ceil(total / perPage)

    return {
      data: paginatedData,
      meta: {
        page,
        perPage,
        total,
        totalPages,
        hasNextPage: page < totalPages,
        hasPreviousPage: page > 1
      }
    }
  }
}
`;
  }

  generateRuntimeErrors(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

/**
 * Base error class for Lenz client runtime errors.
 */
export class LenzClientError extends Error {
  public readonly code: string
  public readonly details?: Record<string, any>

  constructor(code: string, message: string, details?: Record<string, any>) {
    super(message)
    this.name = 'LenzClientError'
    this.code = code
    this.details = details
  }
}

/** Duplicate key / unique constraint violation */
export class UniqueConstraintError extends LenzClientError {
  constructor(key?: string, details?: Record<string, any>) {
    super(
      'UNIQUE_CONSTRAINT',
      \`Unique constraint violation\${key ? ' on field: ' + key : ''}\`,
      { key, ...details }
    )
    this.name = 'UniqueConstraintError'
  }
}

/** Record not found */
export class NotFoundError extends LenzClientError {
  constructor(modelName?: string, details?: Record<string, any>) {
    super(
      'NOT_FOUND',
      \`Record not found\${modelName ? ' in ' + modelName : ''}\`,
      { modelName, ...details }
    )
    this.name = 'NotFoundError'
  }
}

/** Validation error */
export class ValidationError extends LenzClientError {
  constructor(message: string, details?: Record<string, any>) {
    super('VALIDATION_ERROR', message, details)
    this.name = 'ValidationError'
  }
}

/** Connection / network error */
export class ConnectionError extends LenzClientError {
  constructor(message: string, details?: Record<string, any>) {
    super('CONNECTION_ERROR', message, details)
    this.name = 'ConnectionError'
  }
}

/** Transaction error */
export class TransactionError extends LenzClientError {
  constructor(message: string, details?: Record<string, any>) {
    super('TRANSACTION_ERROR', message, details)
    this.name = 'TransactionError'
  }
}

const MONGODB_ERROR_MAP: Record<number, string> = {
  11000: 'Unique constraint violation: a record with this value already exists',
  11001: 'Unique constraint violation',
  121: 'Document failed validation',
  13: 'Authentication failed: invalid credentials',
  18: 'Authentication failed',
  6: 'Host unreachable: could not connect to the database',
  9001: 'Socket error: connection to the database was lost',
  43: 'Cursor not found: the query cursor has expired',
  50: 'Query exceeded maximum execution time',
  13435: 'Not a primary or secondary: the database is not available for reads',
  100: 'Cannot replicate: the operation could not be completed',
  11600: 'Operation interrupted: the database is shutting down',
  11601: 'Operation interrupted',
  91: 'Shutdown in progress',
  133: 'Failed to connect: could not reach the database server',
  123: 'Operation exceeded the allowed time limit',
  64: 'Write concern error: not enough replicas to acknowledge the write',
  10001: 'Write concern failed',
  16029: 'Query produced a result set that exceeds the maximum allowed size',
  16819: 'Sort operation used more than the maximum 32 megabytes of RAM',
  17144: 'Cursor timeout: the cursor timed out due to inactivity',
}

export function wrapMongoError(error: any, context?: string): LenzClientError {
  if (error instanceof LenzClientError) return error

  const mongoCode = error?.code || error?.errorLabels?.length ? undefined : undefined
  const codeNum = typeof mongoCode === 'number' ? mongoCode : error?.code
  const message = error?.message || String(error)

  if (codeNum && MONGODB_ERROR_MAP[codeNum]) {
    switch (codeNum) {
      case 11000:
      case 11001: {
        const keyMatch = message.match(/index:\\s*(?:\\{|\\{.*:)\\s*([^\\}]+)\\s*\\}/)
        const key = keyMatch ? keyMatch[1].trim() : undefined
        return new UniqueConstraintError(key, { originalError: message, context })
      }
      case 13:
      case 18:
        return new ConnectionError(MONGODB_ERROR_MAP[codeNum] + (context ? ' [' + context + ']' : ''), { originalError: message, context })
      case 6:
      case 9001:
      case 133:
        return new ConnectionError(MONGODB_ERROR_MAP[codeNum], { originalError: message, context })
      default:
        return new LenzClientError('DATABASE_ERROR', MONGODB_ERROR_MAP[codeNum] + (context ? ' [' + context + ']' : ''), {
          code: codeNum,
          originalError: message,
          context
        })
    }
  }

  if (message.includes('not found') || message.includes('NotFound')) {
    return new NotFoundError(context, { originalError: message })
  }
  if (message.includes('Invalid objectId') || message.includes('ObjectId')) {
    return new ValidationError('Invalid ID format', { originalError: message, context })
  }
  if (message.includes('timed out') || message.includes('timeout')) {
    return new ConnectionError('Database operation timed out', { originalError: message, context })
  }
  if (message.includes('Transaction') && (message.includes('abort') || message.includes('fail'))) {
    return new TransactionError('Transaction failed: ' + message, { originalError: message, context })
  }

  return new LenzClientError('UNKNOWN_ERROR', message, { context })
}
`;
  }

  generateRuntimeLogger(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

export type LogLevel = 'query' | 'info' | 'warn' | 'error'
export type LogEmit = 'stdout' | 'event'

export interface LogDefinition {
  emit: LogEmit
  level: LogLevel
}

export interface QueryEvent {
  query: string
  params: any[]
  duration: number
  operation: string
  collection: string
  timestamp: Date
}

export interface LogEvent {
  level: LogLevel
  message: string
  timestamp: Date
}

type LogCallback = (event: QueryEvent | LogEvent) => void

export class Logger {
  private logConfig: (LogLevel | LogDefinition)[]
  private eventListeners: Map<string, LogCallback[]> = new Map()

  constructor(logConfig?: (LogLevel | LogDefinition)[]) {
    this.logConfig = logConfig || []
  }

  private shouldLog(level: LogLevel): boolean {
    for (const entry of this.logConfig) {
      if (typeof entry === 'string') {
        if (entry === level) return true
      } else {
        if (entry.level === level && entry.emit === 'event') {
          return true
        }
      }
    }
    return false
  }

  private shouldEmitStdout(level: LogLevel): boolean {
    for (const entry of this.logConfig) {
      if (typeof entry === 'string') {
        if (entry === level) return true
      } else {
        if (entry.level === level && entry.emit === 'stdout') return true
      }
    }
    return false
  }

  private shouldEmitEvent(level: LogLevel): boolean {
    for (const entry of this.logConfig) {
      if (typeof entry !== 'string' && entry.level === level && entry.emit === 'event') {
        return true
      }
    }
    return false
  }

  query(event: QueryEvent): void {
    const evt: LogEvent = {
      level: 'query',
      message: \`\${event.operation} \${event.collection} \${event.duration}ms - \${event.query}\`,
      timestamp: event.timestamp
    }
    if (this.shouldEmitStdout('query')) {
      console.log('lenz:query', evt.message)
    }
    if (this.shouldEmitEvent('query')) {
      this.emit('query', event)
    }
  }

  info(message: string): void {
    if (this.shouldEmitStdout('info')) {
      console.log('lenz:info', message)
    }
    if (this.shouldEmitEvent('info')) {
      this.emit('info', { level: 'info', message, timestamp: new Date() })
    }
  }

  warn(message: string): void {
    if (this.shouldEmitStdout('warn')) {
      console.warn('lenz:warn', message)
    }
    if (this.shouldEmitEvent('warn')) {
      this.emit('warn', { level: 'warn', message, timestamp: new Date() })
    }
  }

  error(message: string): void {
    if (this.shouldEmitStdout('error')) {
      console.error('lenz:error', message)
    }
    if (this.shouldEmitEvent('error')) {
      this.emit('error', { level: 'error', message, timestamp: new Date() })
    }
  }

  on(event: string, callback: LogCallback): void {
    if (!this.eventListeners.has(event)) {
      this.eventListeners.set(event, [])
    }
    this.eventListeners.get(event)!.push(callback)
  }

  private emit(event: string, data: any): void {
    const listeners = this.eventListeners.get(event)
    if (listeners) {
      for (const cb of listeners) {
        try {
          cb(data)
        } catch { /* swallow listener errors */ }
      }
    }
  }

  child(context: string): Logger {
    return this
  }
}
`;
  }

  generateRuntimeIndex(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

export { QueryBuilder } from './query'
export { PaginationHelper } from './pagination'
export { RelationResolver } from './relations'
export { Logger } from './logger'
export type { LogLevel, LogDefinition, QueryEvent, LogEvent } from './logger'
export {
  LenzClientError,
  UniqueConstraintError,
  NotFoundError,
  ValidationError,
  ConnectionError,
  TransactionError,
  wrapMongoError
} from './errors'
`;
  }

  generateRuntimeQuery(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

import { ObjectId, Filter, UpdateFilter } from 'mongodb'
import type { WhereInput, QueryOptions, SelectInput } from '../types'
import { PaginationHelper } from './pagination'

export class QueryBuilder {
  static buildWhere<T>(where: WhereInput<T>): Filter<any> {
    const filter: Filter<any> = {}

    for (const [key, value] of Object.entries(where || {})) {
      if (key === 'id') {
        if (typeof value === 'object' && value !== null) {
          this.applyOperators(filter, '_id', value)
        } else {
          filter._id = this.normalizeId(value)
        }
      } else if (key === 'search') {
        if (typeof value === 'string' && value.length > 0) {
          filter.$text = { $search: value }
        }
      } else if (key === 'AND') {
        if (value !== null && typeof value === 'object') {
          const conditions = Array.isArray(value) ? value : [value]
          filter.$and = conditions.map(cond => this.buildWhere(cond))
        }
      } else if (key === 'OR') {
        if (value !== null && typeof value === 'object') {
          const conditions = Array.isArray(value) ? value : [value]
          filter.$or = conditions.map(cond => this.buildWhere(cond))
        }
      } else if (key === 'NOT') {
        if (value !== null && typeof value === 'object') {
          filter.$not = this.buildWhere(value)
        }
      } else if (typeof value === 'object' && value !== null) {
        this.applyOperators(filter, key, value)
      } else {
        filter[key] = value
      }
    }

    return filter
  }

  static buildCursorCondition(
    cursor: string | ObjectId,
    orderBy: any = { _id: 'asc' }
  ): Filter<any> {
    const cursorId = typeof cursor === 'string'
      ? PaginationHelper.parseCursor(cursor)
      : cursor.toString()

    if (orderBy._id || (!Object.keys(orderBy).length)) {
      return {
        _id: { $gt: new ObjectId(cursorId) }
      }
    }

    const orderField = Object.keys(orderBy)[0]
    const orderDirection = orderBy[orderField]

    return {
      [orderField]: orderDirection === 'desc'
        ? { $lt: cursorId }
        : { $gt: cursorId }
    }
  }

  static buildProjection<T>(
    select: SelectInput | undefined,
    hiddenFields: string[] = [],
    omit?: SelectInput,
    fieldMapping?: Record<string, string>
  ): any {
    const mapField = (name: string): string => fieldMapping?.[name] || name;

    if (omit && !select) {
      const projection: any = {};
      for (const [key, value] of Object.entries(omit)) {
        if (value) projection[mapField(key)] = 0;
      }
      hiddenFields.forEach(field => { projection[mapField(field)] = 0; });
      return Object.keys(projection).length > 0 ? projection : undefined;
    }

    if (!select) {
      if (hiddenFields.length === 0) return undefined;
      const projection: any = {};
      hiddenFields.forEach(field => {
        projection[mapField(field)] = 0;
      });
      return projection;
    }

    const projection: any = {};
    const processSelect = (sel: SelectInput, prefix = '') => {
      for (const [key, value] of Object.entries(sel)) {
        const mappedKey = prefix ? key : mapField(key);
        const fullPath = prefix ? \`\${prefix}.\${key}\` : mappedKey;

        if (typeof value === 'boolean') {
          projection[fullPath] = value ? 1 : 0;
        } else {
          processSelect(value, fullPath);
        }
      }
    };

    processSelect(select);

    hiddenFields.forEach(field => {
      if (projection[field] === undefined) {
        projection[field] = 0;
      }
    });

    return projection;
  }

  static buildOptions<T>(options: QueryOptions<T>, hiddenFields: string[] = [], fieldMapping?: Record<string, string>): any {
    const result: any = {}

    if (options.skip !== undefined) result.skip = options.skip
    if (options.take !== undefined) result.limit = options.take

    if (options.orderBy) {
      result.sort = this.buildSort(options.orderBy)
    }

    if (options.session) {
      result.session = options.session
    }

    const projection = this.buildProjection(options.select, hiddenFields, options.omit, fieldMapping)
    if (projection) {
      result.projection = projection
    }

    return result
  }

  static buildSort(orderBy: any): any {
    if (Array.isArray(orderBy)) {
      return orderBy.reduce((acc, curr) => ({ ...acc, ...this.buildSort(curr) }), {})
    }

    const sort: any = {}
    for (const [field, direction] of Object.entries(orderBy)) {
      if (direction === 'asc' || direction === 1) {
        sort[field] = 1
      } else if (direction === 'desc' || direction === -1) {
        sort[field] = -1
      }
    }
    return sort
  }

  private static applyOperators(filter: any, field: string, operators: any): void {
    let targetField = field;
    const pathArr = operators.path;
    if (Array.isArray(pathArr) && pathArr.length > 0) {
      targetField = pathArr.reduce((acc: string, p: string) => \`\${acc}.\${p}\`, field);
    }

    const mode = operators.mode;
    const isInsensitive = mode === 'insensitive';

    const mongoOperators: Record<string, string> = {
      equals: '$eq',
      not: '$ne',
      in: '$in',
      notIn: '$nin',
      lt: '$lt',
      lte: '$lte',
      gt: '$gt',
      gte: '$gte',
      contains: '$regex',
      startsWith: '$regex',
      endsWith: '$regex'
    }

    for (const [op, value] of Object.entries(operators)) {
      if (op === 'path') continue;
      if (op === 'mode') continue;

      if (op === 'string_contains') {
        filter[targetField] = { $regex: value, $options: 'i' };
        continue;
      }
      if (op === 'string_starts_with') {
        filter[targetField] = { $regex: \`^\${value}\`, $options: 'i' };
        continue;
      }
      if (op === 'string_ends_with') {
        filter[targetField] = { $regex: \`\${value}\$\`, $options: 'i' };
        continue;
      }

      if (op === 'has') {
        filter[targetField] = { $elemMatch: { $eq: value } };
        continue;
      }
      if (op === 'hasEvery') {
        if (Array.isArray(value)) {
          filter[targetField] = { $all: value };
        }
        continue;
      }
      if (op === 'hasSome') {
        if (Array.isArray(value)) {
          filter[targetField] = { $in: value };
        }
        continue;
      }
      if (op === 'isEmpty') {
        filter[targetField] = { $exists: true, $size: 0 };
        continue;
      }
      if (op === 'equals') {
        if (Array.isArray(value)) {
          filter[targetField] = { $eq: value };
        }
        continue;
      }

      // Geo-spatial operators (MongoDB)
      if (op === 'near' || op === 'nearSphere') {
        const mongoOp = op === 'near' ? '$near' : '$nearSphere';
        if (value && typeof value === 'object') {
          const geoValue: any = {};
          if (value.type && value.coordinates) {
            geoValue.$geometry = { type: value.type, coordinates: value.coordinates };
          }
          if (value.maxDistance !== undefined) geoValue.$maxDistance = value.maxDistance;
          if (value.minDistance !== undefined) geoValue.$minDistance = value.minDistance;
          filter[targetField] = { [mongoOp]: geoValue };
        }
        continue;
      }
      if (op === 'geoWithin') {
        if (value && typeof value === 'object') {
          filter[targetField] = { $geoWithin: value };
        }
        continue;
      }
      if (op === 'geoIntersects') {
        if (value && typeof value === 'object' && value.$geometry) {
          filter[targetField] = { $geoIntersects: { $geometry: value.$geometry } };
        }
        continue;
      }
      if (op === 'geoContains') {
        if (value && typeof value === 'object' && value.$geometry) {
          filter[targetField] = { $geoContains: { $geometry: value.$geometry } };
        }
        continue;
      }

      if (op === 'array_contains') {
        filter[targetField] = value;
        continue;
      }
      if (op === 'array_starts_with') {
        filter[targetField] = { $elemMatch: { $eq: value } };
        continue;
      }
      if (op === 'array_ends_with') {
        filter[targetField] = value;
        continue;
      }

      const mongoOp = mongoOperators[op]

      if (mongoOp) {
        if (op === 'contains') {
          filter[targetField] = { $regex: value, $options: isInsensitive ? 'i' : '' }
        } else if (op === 'startsWith') {
          filter[targetField] = { $regex: \`^\${value}\`, $options: isInsensitive ? 'i' : '' }
        } else if (op === 'endsWith') {
          filter[targetField] = { $regex: \`\${value}\$\`, $options: isInsensitive ? 'i' : '' }
        } else if (isInsensitive && (op === 'equals' || op === 'not')) {
          const escapedValue = String(value).replace(/[.*+?^\${}()|[\]\\\\]/g, '\\\\$&');
          filter[targetField] = {
            [op === 'equals' ? '$regex' : '$not']: new RegExp(\`^\${escapedValue}\$\`, 'i')
          };
        } else if (isInsensitive && (op === 'in' || op === 'notIn')) {
          if (Array.isArray(value)) {
            const regexes = value.map(v => new RegExp(\`^\${String(v).replace(/[.*+?^\${}()|[\]\\\\]/g, '\\\\$&')}\$\`, 'i'));
            filter[targetField] = { [op === 'in' ? '$in' : '$nin']: regexes };
          }
        } else {
          if (!filter[targetField]) filter[targetField] = {}
          const normalizedValue = targetField === '_id' ? this.normalizeId(value) : value
          filter[targetField][mongoOp] = normalizedValue
        }
      }
    }
  }

  static normalizeId(id: string | ObjectId | (string | ObjectId)[]): ObjectId | string | (ObjectId | string)[] {
    try {
      if (Array.isArray(id)) {
        return id.map(item => this.normalizeId(item) as ObjectId | string)
      }
      if (typeof id === 'string' && /^[0-9a-fA-F]{24}$/.test(id)) {
        return new ObjectId(id)
      }
      return id
    } catch {
      return id
    }
  }

  static buildUpdate(data: any): UpdateFilter<any> {
    const update: UpdateFilter<any> = {}

    const setOperations: any = {}
    const mongoOperators: any = {}

    const atomicOperators = ['increment', 'decrement', 'multiply', 'divide'];
    const arrayOperators = ['push', 'pull', 'addToSet', 'pop', 'pullAll', 'pushAll'];
    const operatorMap: Record<string, string> = {
      push: '$push',
      pull: '$pull',
      addToSet: '$addToSet',
      pop: '$pop',
      pullAll: '$pullAll',
      pushAll: '$pushAll'
    };

    for (const [key, value] of Object.entries(data)) {
      if (key.startsWith('$')) {
        mongoOperators[key] = value
      } else {
        if (typeof value === 'object' && value !== null) {
          const keys = Object.keys(value)

          // Atomic number operations: increment, decrement, multiply, divide
          if (keys.every(k => atomicOperators.includes(k))) {
            const inc: Record<string, number> = {};
            const mul: Record<string, number> = {};
            for (const op of keys) {
              const opValue = value[op];
              if (op === 'increment') { inc[key] = opValue; }
              else if (op === 'decrement') { inc[key] = -opValue; }
              else if (op === 'multiply') { mul[key] = opValue; }
              else if (op === 'divide') { mul[key] = 1 / opValue; }
            }
            if (Object.keys(inc).length > 0) {
              if (!mongoOperators.$inc) mongoOperators.$inc = {};
              Object.assign(mongoOperators.$inc, inc);
            }
            if (Object.keys(mul).length > 0) {
              if (!mongoOperators.$mul) mongoOperators.$mul = {};
              Object.assign(mongoOperators.$mul, mul);
            }
            continue;
          }

          if (keys.length === 1 && arrayOperators.includes(keys[0])) {
            const op = keys[0]
            const opValue = value[op]

            if (op === 'push' || op === 'addToSet') {
              if (typeof opValue === 'object' && opValue !== null && Object.keys(opValue).length === 1 && opValue.each !== undefined) {
                const mongoOp = operatorMap[op]
                if (!mongoOperators[mongoOp]) {
                  mongoOperators[mongoOp] = {}
                }
                mongoOperators[mongoOp][key] = { $each: opValue.each }
                continue
              }
            }

            const mongoOp = operatorMap[op]
            if (!mongoOperators[mongoOp]) {
              mongoOperators[mongoOp] = {}
            }
            mongoOperators[mongoOp][key] = opValue
            continue
          }
        }

        setOperations[key] = value
      }
    }

    if (Object.keys(setOperations).length > 0) {
      update.$set = setOperations
    }

    Object.assign(update, mongoOperators)

    return update
  }
}
`;
  }

  generateRuntimeRelations(): string {
    return `// This file was auto-generated by Lenz. Do not edit manually.
// @generated

import { Db, ObjectId } from 'mongodb'
import { QueryBuilder } from './query'

export class RelationResolver {
  static async resolveOneToOne(
    db: Db,
    sourceCollection: string,
    targetCollection: string,
    sourceId: string,
    foreignKey: string
  ): Promise<any> {
    const collection = db.collection(targetCollection)
    return await collection.findOne({ [foreignKey]: sourceId })
  }

  static async resolveOneToMany(
    db: Db,
    sourceCollection: string,
    targetCollection: string,
    sourceId: string,
    foreignKey: string
  ): Promise<any[]> {
    const collection = db.collection(targetCollection)
    return await collection.find({ [foreignKey]: sourceId }).toArray()
  }

  static async resolveManyToMany(
    db: Db,
    sourceCollection: string,
    targetCollection: string,
    joinCollection: string,
    sourceId: string,
    where?: any,
    orderBy?: any,
    take?: number,
    skip?: number,
    select?: any
  ): Promise<any[]> {
    const joinCol = db.collection(joinCollection)
    const targetCol = db.collection(targetCollection)

    const connections = await joinCol.find({
      [\`\${sourceCollection.toLowerCase()}Id\`]: sourceId
    }).toArray()

    const targetIds = connections.map(c => c[\`\${targetCollection.toLowerCase()}Id\`])

    if (targetIds.length === 0) {
      return []
    }

    let query: any = { _id: { $in: targetIds.map(id => new ObjectId(id)) } }

    if (where && Object.keys(where).length > 0) {
      query = { $and: [query, where] }
    }

    let cursor = targetCol.find(query)

    if (orderBy) {
      cursor = cursor.sort(orderBy)
    }
    if (skip !== undefined && skip !== null) {
      cursor = cursor.skip(skip)
    }
    if (take !== undefined && take !== null) {
      cursor = cursor.limit(take)
    }
    if (select) {
      const projection = QueryBuilder.buildProjection(select, [])
      if (projection) {
        cursor = cursor.project(projection)
      }
    }

    return await cursor.toArray()
  }

  static async countManyToMany(
    db: Db,
    sourceCollection: string,
    targetCollection: string,
    joinCollection: string,
    sourceId: string
  ): Promise<number> {
    const joinCol = db.collection(joinCollection)
    const count = await joinCol.countDocuments({
      [\`\${sourceCollection.toLowerCase()}Id\`]: sourceId
    })
    return count
  }

  static formatDocument(doc: any): any {
    if (!doc) return doc
    const formatted = { ...doc }
    if (formatted._id) {
      formatted.id = formatted._id.toString()
      delete formatted._id
    }
    // Convert BSON types to JS types
    for (const key of Object.keys(formatted)) {
      const val = formatted[key]
      if (val !== null && typeof val === 'object') {
        if (val._bsontype === 'Long') {
          formatted[key] = val.toBigInt()
        } else if (val._bsontype === 'Binary') {
          formatted[key] = Buffer.from(val.buffer)
        }
      }
    }
    return formatted
  }
}
`;
  }
}
